projects:
  workspace: "."
  foo: "packages/foo"
  bar: "packages/bar"
  baz: "packages/baz"
  preview-registry: "apps/preview-registry"
  hello: "apps/hello"

vcs:
  defaultBranch: "main"

pipeline:
  installDependencies: false

telemetry: false
