// AUTO-GENERATED by scripts/publish-on-deploy.ts (production) or
// scripts/stage-local.ts (local dev). The checked-in version is an
// empty stub so a fresh clone still typechecks before any build runs.
import type { PackageRow } from './landing.js'

export const SNAPSHOT_PACKAGES: readonly PackageRow[] = [] as const
